version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - picpay-network

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - picpay-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - picpay-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - picpay-network

  carteira-service:
    command: [ "/carteira/start-carteira.sh" ]
    build:
      context: ./carteira
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  cobrar-service:
    command: [ "/cobrar/start-cobrar.sh" ]
    build:
      context: ./cobrar
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  crypto-service:
    command: [ "/crypto/start-crypto.sh" ]
    build:
      context: ./crypto
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  emprestimos-service:
    command: [ "/emprestimos/start-emprestimos.sh" ]
    build:
      context: ./emprestimos
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  finance-service:
    command: [ "/finance/start-finance.sh" ]
    build:
      context: ./finance
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  investir-service:
    command: [ "/investir/start-investir.sh" ]
    build:
      context: ./investir
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  notificacoes-service:
    command: [ "/notificacoes/start-notificacoes.sh" ]
    build:
      context: ./notificacoes
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  pagar-service:
    command: [ "/pagar/start-pagar.sh" ]
    build:
      context: ./pagar
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  sacar-service:
    command: [ "/sacar/start-sacar.sh" ]
    build:
      context: ./sacar
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

  seguros-service:
    command: [ "/seguros/start-seguros.sh" ]
    build:
      context: ./seguros
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mongo
      - kafka
    networks:
      - picpay-network

networks:
  picpay-network:
    driver: bridge
